### ISSUE TITLE
pugixml v1.11.4 released 

### ISSUE THREAD

**Issue by aismann** [c4games/engine-x#334]

**Comment by halx99** [comment]
I have checked, no sources change since 1.11.0, so no need to upgrade

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: aismann ***@***.***>
Sent: Tuesday, March 16, 2021 2:29:02 AM
To: c4games/engine-x ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [c4games/engine-x] pugixml v1.11.4 released (#334)

**Comment by halx99** [comment]
see: https://github.com/zeux/pugixml/compare/v1.11...master
