### ISSUE TITLE
Support switch GLES backend for google/angle

### ISSUE THREAD

**Issue by halx99** [c4games/engine-x#99]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
https://github.com/google/angle

**Comment by RustyMoyher** [comment]
Awesome! Does this mean ANGLE now works with win32 builds?

**Comment by halx99** [comment]
Yeah, It's works, but 2 things you should review:
  * Currently, it's control by new macro 'CC_USE_GLES_ON_DESKTOP' at CCPlatformMacros.h, and defined as 1
  * You should compile angle by your self

Later, I will upload binaries of angle build with vs2019, and maybe all 3rd libs will be build with the same toolset of vs2019

**Comment by halx99** [comment]
there is a 1k build script: https://github.com/simdsoft/angle-patch/blob/master/build-release-vs2019.bat
when you already install vs2019 with win10sdk

just put it to parent directory of angle root and run it

**Comment by halx99** [comment]
AH, lost a things, you shoud also read google dev guide of angle to setup build env gn works well, or a simple way, just copy libGLESv2.dll libEGL.dll d3dcompiler_47.dll from chrome x86 install location to cpp-tests build bin directory

**Comment by halx99** [comment]
Now win32 builds can run with angle properly.

**Comment by RustyMoyher** [comment]
Awesome! I was able to get it working with the new ANGLE dlls you included. (I eventually got ANGLE building yesterday, but wow, that is a complex tool chain to setup!)

I believe the default ANGLE renderer on win32 uses Direct3D 11. It would be helpful to be able to specify the ANGLE backend renderer. For instance to use Direct3D11on12 or Vulkan. Normally this is done by using eglGetPlatformDisplayEXT and passing in display attributes before the window is created. In our case we're using GLFW instead of creating the window ourselves, so I'm not sure how tricky it would be to add.

I'm mostly familiar with eglGetPlatformDisplayEXT from using it in UWP builds. For example, here is how to enable D3D11ON12:

	const EGLint defaultDisplayAttributes[] =
	{
		EGL_PLATFORM_ANGLE_TYPE_ANGLE, EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
		EGL_PLATFORM_ANGLE_D3D11ON12_ANGLE, EGL_TRUE,
		EGL_NONE,
	};

	EGLConfig config = NULL;

	// eglGetPlatformDisplayEXT is an alternative to eglGetDisplay. It allows us to pass in display attributes, used to configure D3D11.
	PFNEGLGETPLATFORMDISPLAYEXTPROC eglGetPlatformDisplayEXT = reinterpret_cast<PFNEGLGETPLATFORMDISPLAYEXTPROC>(eglGetProcAddress("eglGetPlatformDisplayEXT"));
	if (!eglGetPlatformDisplayEXT) {
		throw Exception::CreateException(E_FAIL, L"Failed to get function eglGetPlatformDisplayEXT");
	}

	// This tries to initialize EGL to D3D11 Feature Level 10_0+. See above comment for details.
	mEglDisplay = eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, EGL_DEFAULT_DISPLAY, defaultDisplayAttributes);
	if (mEglDisplay == EGL_NO_DISPLAY) {
		throw Exception::CreateException(E_FAIL, L"Failed to get EGL display");
	}

**Comment by halx99** [comment]
Yes, maybe we need mofiy glfw source code to provide eglGetDisplayCallback for user to setup display attributes. so maybe, we can submit a issue about this.

**Comment by halx99** [comment]
@RustyMoyher hi, I submit a issue to ```glfw```: https://github.com/glfw/glfw/issues/1718

**Comment by RustyMoyher** [comment]
Nice. Good call!

I have a more radical suggestion: Replace GLFW with SDL2.

I’ve been using SDL2 with cocos2d-x since 2015 for audio, controller input, and haptic feedback. I think both GLFW and SDL2 are good products, but for me using GLFW is a bit redundant and I’m integrating more of the SDL2 feature set as my products develop. SDL2 already works well with BGFX, has a good Nintendo Switch port and feels like a natural choice for my games going forward.

I’m not sure how this aligns with your goals for Engine-X, but it’s something I’d love to have.

**Comment by halx99** [comment]
Mybe I need take time to research about SDL2 to cocos2d-x
